from enum import StrEnum

__all__ = ["DouCategory", "DjinniCategory"]


class DouCategory(StrEnum):
    JAVA = "Java"
    PYTHON = "Python"
    DOTNET = ".NET"
    AIML = "AI/ML"
    PHP = "PHP"
    GOLANG = "Golang"
    CPP = "C++"
    IOS_MACOS = "iOS/macOS"
    QA = "QA"
    ANDROID = "Android"
    FRONTEND = "Front End"
    PROJECT_MANAGER = "Project Manager"
    PRODUCT_MANAGER = "Product Manager"
    HR = "HR"
    NODE_JS = "Node.js"
    DESIGN = "Design"
    SALES = "Sales"
    MARKETING = "Marketing"
    ANALYST = "Analyst"
    DEVOPS = "DevOps"
    MILTECH = "Miltech"
    GOVTECH = "Govtech"
    ACCOUNT_MANAGER = "Account Manager"
    ANIMATOR = "Animator"
    ARCHITECT = "Architect"
    BIG_DATA = "Big Data"
    DATA_ENGINEER = "Data Engineer"
    EMBEDDED = "Embedded"
    FINANCE = "Finance"
    RUBY = "Ruby"
    SUPPORT = "Support"
    SYSADMIN = "SysAdmin"
    HARDWARE = "Hardware"
    DATA_SCIENCE = "Data Science"


class DjinniCategory(StrEnum):
    JAVASCRIPT = "JavaScript"
    ANGULAR = "Angular"
    REACTJS = "React.js"
    VUEJS = "Vue.js"
    SVELTE = "Svelte"
    FULLSTACK = "Fullstack"
    JAVA = "Java"
    DOTNET = ".NET"
    PHP = "PHP"
    PYTHON = "Python"
    NODE_JS = "Node.js"
    IOS = "iOS"
    ANDROID = "Android"
    REACT_NATIVE = "React Native"
    C = "C"
    FLUTTER = "Flutter"
    GOLANG = "Golang"
    RUBY = "Ruby"
    SCALA = "Scala"
    SALESFORCE = "Salesforce"
    RUST = "Rust"
    ELIXIR = "Elixir"
    KOTLIN = "Kotlin"
    ERP = "ERP"
    QA_MANUAL = "QA"
    QA_AUTOMATION = "QA Automation"
    DESIGN = "Design"
    GAMEDEV = "Unity"
    PROJECT_MANAGER = "Project Manager"
    PRODUCT_MANAGER = "Product Manager"
    DEVOPS = "DevOps"
    BUSINESS_ANALYST = "Business Analyst"
    DATA_SCIENCE = "Data Science"
    DATA_ANALYST = "Data Analyst"
